name = "openai-cf"
main = "index.js"
compatibility_date = "2024-05-06"

[ai]
binding = "AI" # i.e. available in your Worker on env.AI

[[r2_buckets]]
binding = "IMAGE_BUCKET"
bucket_name = "openai-cf-images"
preview_bucket_name = "ai-images"

[vars]
ACCESS_TOKEN = "$AI_API_ACCESS_TOKEN"
# MODEL_MAPPER = { "gpt-3.5-turbo" = "@cf/meta/llama-2-7b-chat-int8" } # Optional